// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://palsvxngzywrwbuccvdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhbHN2eG5nenl3cndidWNjdmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjI5NjAsImV4cCI6MjA2MTgzODk2MH0._YB2YpXcJ0pGntTBWQF546EearBZp9iJ7S60wlSAKzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);